# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  name: salt_solo
  formula: users
  state_top:
    base:
      "*":
        - users

platforms:
  - name: bento/debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        users.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - users

